infosysnet/index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('index/remark1/', views.Remark1View.as_view(), name='remark1'),
    path('index/remark2/', views.Remark2View.as_view(), name='remark2'),
    path('index/remark3/', views.Remark3View.as_view(), name='remark3'),
    path('forbidden/', views.ForbiddenClass.as_view(), name='forbidden'),
    path('index/flag/', views.FlakeFlagClass.as_view(), name='fakeflag'),
    path('index/index/', views.FlagClass.as_view(), name='flag'),
]

infosysnet/infosysnet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('infosysnet/', include('index.urls', namespace="index")),
    path('admin/', admin.site.urls),
]

infosysnet/index/models.py
from django.db import models

# Create your models here.

infosysnet/index/forms.py
from django import forms


class FlagForm(forms.Form):
    name = forms.CharField(label='Name')
    password = forms.CharField(label='Password')

infosysnet/index/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .forms import FlagForm
from infosysnet import settings


class TopView(TemplateView):
    template_name = 'index/top.html'


class IndexView(TemplateView):
    template_name = 'index/index.html'


class Remark1View(TemplateView):
    template_name = 'index/remark1.html'


class Remark2View(TemplateView):
    template_name = 'index/remark2.html'


class Remark3View(TemplateView):
    template_name = 'index/remark3.html'


class ForbiddenClass(TemplateView):
    template_name = 'index/forbidden.html'


class FlakeFlagClass(TemplateView):
    template_name = 'index/fakeflag.html'


class FlagClass(TemplateView):
    form_class = FlagForm
    template_name = 'index/flag.html'

    def __init__(self, **kwargs):
        self.params = {
            'form': FlagForm()
        }

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(FlagClass, self).dispatch(*args, **kwargs)

    def get(self, request):
        return render(request, 'index/flag.html', self.params)

    def post(self, request):
        name = request.POST['name']
        password = request.POST['password']

        if name == settings.NAME and password == settings.PASSWORD:
            return render(request, 'index/flag2.html')

        return render(request, 'index/flag.html', self.params)

infosysnet/index/templates/index/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>渡辺研究室 | 大阪大学 大学院情報科学研究科 情報ネットワーク学専攻　工学部 電子情報工学科 情報通信工学科目</title>
  </head>
  <body>
    <h1>渡辺研究室 | 大阪大学 大学院情報科学研究科 情報ネットワーク学専攻 | 研究内容紹介</h1>
    <div>
      <a href="{% url 'index:index' %}" style='font-size: 20px;'>全体概要</a>&nbsp;
      <a href="{% url 'index:remark1' %}" style='font-size: 20px;'>IoT/M2M  Sensor Networks</a>&nbsp;
      <a href="{% url 'index:remark2' %}" style='font-size: 20px;'>深層学習×映像伝送</a>&nbsp;
      <a href="{% url 'index:remark3' %}" style='font-size: 20px;'>VR/AR Multimedia Networks</a>&nbsp;
    </div>
    <hr>
    {% block content %}{% endblock %}
    <hr>
  </body>
</html>

infosysnet/index/templates/index/fakeflag.html
{% extends 'index/base.html' %}

{% block content %}
<h1>Congratulations !!!</h1>
<h1 style="color:red">{{ FLAG1 }}</h1>
<h1>You got 1 points !!!</h1>
<h1>However, in actual, another flag is other place !!!</h1>
<h1>Can you find that ???</h1>
{% endblock %}

infosysnet/index/templates/index/flag.html
<form method="post">
<br/>
{{ form }}
<button type="submit">submit</button>
</form>
<h1>I give a hint. Name is admin. Password's length is three and password is lower case.</h1>

infosysnet/index/templates/index/flag2.html
{% load static %}

<h1 style="color:red">{{ FLAG2 }}</h1>
<img src="{% static 'index/wani.png' %}" width="100" height="100">

infosysnet/index/templates/index/forbidden.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access what you want on this server.</p>
<hr>
<address>Apache/2.2.15 Server at Raspberry Pi Port 10080</address>
</body></html>

infosysnet/index/templates/index/index.html
{% extends 'index/base.html' %}

{% block content %}
<div>
  <p>
    インテリジェントネットワーク講座ではネットワーク技術を中心に、インターネットの次、携帯電話の次、無線LANの次を実現する技術を研究しています。現代でも重要なコンピュータネットワークですが、より高度なサービスやアプリケーションを提供すべくさらなる進化を遂げようとしています。例えばネットワークを介した遠隔手術。今はまだ制約が多いため不可能です。しかしながら、長距離をリアルタイムにかつ高信頼に情報交換が可能なコンピュータネットワークを開発できれば、人間の医者の指示に従う医療ロボットが人間の能力と同じ精度、場合によっては人間を超えた精度で世界中どこでも手術が受けることができるようになります。インテリジェントネットワーク講座では、このような高度な応用を実現するコンピュータネットワークの研究を行っています。
  </p>
  <p>
    研究に関連する主なキーワードはB5G/6G、IoT/M2M、VR/ARです。
    図1に示すように、ネットワークを中心に3つの領域が相互に関わりながら研究を進めています。
  </p>
  <p>
    B5G (Beyond 5G)と6Gは2020年にリリースされる予定の5Gのさらに次のワイヤレスネットワークを意味する言葉です。
    5G、さらに言うとLTEの段階で既にIoTは適用領域として視野に入っています。
    本講座では、本来は音声ネットワークであった携帯電話網、高速データ通信用として発展してきた無線LAN、IoTを対象としたIEEE 802.15.4やBluetoothなどの様々な観点から、新しい時代のワイヤレスネットワーク技術のあるべき姿に向けて取り組んでいます。
  </p>
  <p>
    IoT (Internet-of-Things)とM2M (Machine-to-Machine)はモノがネットワークに接続された状態を意味する言葉です。元来、ネットワークは人と人とを接続する技術でした。
    2000年ごろから徐々にモノをネットワークに接続する試みが開始され、今や車、自動販売機、ドローン、腕時計、テレビ、眼鏡、歯ブラシなど既に多くのモノがネットワークに接続され始めています。
    そしてモノをネットワークに接続するためにはワイヤレスネットワークが不可欠です。
  </p>
  <p>
    VR (Virtual Reality)やAR (Augmented Reality)は人間の現実(Reality)を変容させる技術を意味する言葉です。
    コンピュータネットワークが織りなす電脳空間にHMD (Head Mounted Display)などのデバイスを介して人間自体が入り込むのがVR、電脳空間が物理空間に染み出した状態が拡張現実であると捉えています。
    そしてVRやARの根幹となるHMD (Head Mounted Display)や360度カメラはモノがネットワークに繋がるという意味ではIoTデバイスに含まれます。
  </p>
  <p>
    In our intelligent network laboratory, we are studying network technologies that realize the next generation Internet, mobile phones, and wireless LANs. Although it is an important computer network in modern times, it is significantly evolving to provide more advanced services and applications. For example, remote surgery via a network is impossible now because there are still many restrictions. However, if a computer network capable of exchanging information over a long distance in real time and with high reliability can be developed, a medical robot that complies with the instructions of a human doctor can acquire the same accuracy as human ability. In some cases, we will be able to undergo surgery with higher-precisional surgery operated by the robot than human. In the intelligent network laboratory, we are researching computer networks that realize such advanced applications.
  </p>
  <p>
    Research keywords are B5G / 6G, IoT / M2M, VR / AR.
    As shown in Fig. 1, three areas are mainly involved in the network, and research is under way with mutual involvement.
  </p>
  <p>
    B5G (Beyond 5G) and 6G are the words meaning the next generation wireless network of 5G scheduled to be released in 2020.
    5G, or even at the stage of LTE, IoT has already come into view as an application area.
    In this laboratory, we are working towards B5G / 6G from various viewpoints such as mobile phone network which was originally a voice network, wireless LAN which has been developed for high speed data communication, IEEE 802.15.4 for IoT and Bluetooth It is.
  </p>
  <p>
    IoT (Internet-of-Things) and M2M (Machine-to-Machine) are words meaning that things are connected to the network. Originally, the network was a technology to connect person to person.
    Attempts to gradually connect things to the network began around 2000, and now many cars, vending machines, drone, wrist watches, televisions, glasses, toothbrushes, etc. are already connected to the network.
    And wireless network is essential technology to connect things to the network.
  </p>
  <p>
    VR (Virtual Reality) and AR (Augmented Reality) are words that mean technology that transforms human reality.
    We think that the state in which humans themselves enter through the devices such as HMD (Head Mounted Display) and the like in the computer network interworking space seeps into the physical space as VR, augmented space is augmented reality.
    And HMD (Head Mounted Display) and 360 degree camera which are the basis of VR and AR are included in IoT device in the sense that things are connected to the network.
  </p>
</div>
{% endblock %}

infosysnet/index/templates/index/remark1.html
{% extends 'index/base.html' %}

{% block content %}
<div>
  <p>
    ワイヤレス技術の隆盛によってモノがネットワークに接続される「IoT (Internet-of-Things)」の時代が訪れつつあります。IoTが実現されることで我々の生活するこの物理空間の情報をコンピュータ上で扱うことが可能となり、新しいサービスを実現することができます。例えば、ドローンによる生活空間でのサービス、自動運転車、機器内センサネットワークなどを実現するためにはネットワーク技術の進化不可欠です。本講座では、センサからの情報を取り込むためのセンサネットワークや電波を用いてレーダーのようにダイレクトに物理空間の状態を抽出するワイヤレスセンシング、無線アクセスポイントから電力を伝送する無線電力伝送などの基礎研究から、崩壊現象のビッグデータを取得する軍艦島モニタリングの計測システムやクラウドサービスなどの応用研究まで幅広く取り組んでいます。
  </p>
  <p>
    The era of "Internet - of - Things (IoT)" where things are connected to the network by the prosperity of wireless technology is coming. By realizing IoT, it becomes possible to handle information on this physical space living our lives on computer, and we can realize new service. For example, evolution of network technology is indispensable to realize service in living space by drone, automatic driving car, in-device sensor network, etc. In this course, basic research such as wireless sensing that extracts the state of the physical space directly like a radar using a sensor network for capturing information from the sensor or radio waves, and wireless power transmission that transmits power from the wireless access point We are also working extensively on applied research such as war ship island monitoring which acquires big data of collapse phenomenon.
  </p>
</div>
{% endblock %}

infosysnet/index/templates/index/remark2.html
{% extends 'index/base.html' %}

{% block content %}
<div>
  <p>
    本研究室では、ビデオ通話の映像トラヒックを削減する方式として、深層学習におけるGAN (Generative Adversarial Networks)による映像復元技術を用いた手法を研究しています。
    一般的に、映像データはデータ量が大きいため、ビデオ通話の使用率の上昇は通信帯域のひっ迫を招きます。
    スマートフォンの普及によってコミュニケーションの手段としてビデオ通話が頻繁に使われるようになりました。
  </p>
  <p>
    GANとは、2つの異なる機能をもったニューラルネットワークを競争させることで、学習器自体に学習データに似たデータを生成させることができる技術です。例えば、「1. ある映像が人であるかどうかを判別するニューラルネットワーク」と「2. 人の映像を生成するニューラルネットワーク」を競争させながら学習を行うことで、本物と見分けのつかない人の映像を生成することができるようになります。
  </p>
  <p>
    Generally, since the amount of video data is large, the rise in the usage rate of video calls leads to tightness of the communication band.
    With the spread of smartphones, video calls have been used frequently as a means of communication.
    In this laboratory, we are studying a method using image reconstruction technology by GAN (Generative Adverarial Networks) in deep learning as a method to reduce video traffic of video calls.
  </p>
  <p>
    The GAN is a technology that allows learners themselves to generate data similar to learning data by competing neural networks with two different functions. For example, by conducting learning while competing "1. Neural network to judge whether a certain image is a person" and "2. Neural network to generate a person 's image", it is possible for people who are indistinguishable from genuine You will be able to generate video.
  </p>
</div>
{% endblock %}

infosysnet/index/templates/index/remark3.html
{% extends 'index/base.html' %}

{% block content %}
<div>
  <p>
  4K映像、ヘッドマウントマウントディスプレイ、全天球映像、多視点映像などさまざまな映像撮影技術やディスプレイ技術が登場しています。これらの技術は未来のVR（仮想現実: Virtual Reality）やAR（拡張現実: Augmented Reality）を実現するために不可欠な技術です。映像入力装置と映像出力装置をネットワークを介して接続することで、物理的に離れた空間やコンピュータ上の仮想空間を融合することが可能となります。本講座では、これら超臨場感映像を有線ネットワークや無線ネットワークを介して効率的に伝送するための通信方式の研究や、ネットワークゲームを提供するためのネットワークシステムやクラウドサービスなどの研究を行っています。
  </p>
  <p>
    Various video shooting technologies and display technologies such as 4K video, head mount mounted display, full celestial picture, multi-view video, etc. are appearing. These technologies are indispensable technologies to realize future VR (Virtual Reality) and AR (Augmented Reality). By connecting the video input device and the video output device via the network, it becomes possible to fuse the physically remote space and the virtual space on the computer. In this course, we are conducting research on communication methods to efficiently transmit these super-realistic images via wired networks and wireless networks.
  </p>
</div>
{% endblock %}

infosysnet/index/templates/index/top.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /infosysnet</title>
 </head>
 <body>
<h1>Index of /infosysnet</h1>
<table>
    <tr>
        <th><img src="" alt="[ICO]"></th>
        <th><a href="">Name</a></th>
        <th><a href="">Last modified</a></th>
        <th><a href="">Size</a></th>
        <th><a href="">Description</a></th>
    </tr>
    <tr>
        <th colspan="5"><hr></th>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[DIR]"></td>
        <td><a href="{% url 'index:top' %}">Parent Directory</a></td>
        <td>&nbsp;</td><td align="right">  - </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[TXT]"></td>
        <td><a href="{% url 'index:forbidden' %}">remark1.txt</a></td>
        <td align="right">09-Jan-2019 08:00  </td>
        <td align="right"> 19K</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[TXT]"></td>
        <td><a href="{% url 'index:forbidden' %}">remark2.txt</a></td>
        <td align="right">09-Jan-2019 08:00  </td>
        <td align="right"> 21K</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[TXT]"></td>
        <td><a href="{% url 'index:forbidden' %}">remark3.txt</a></td>
        <td align="right">09-Jan-2019 08:00  </td>
        <td align="right">5.9K</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[TXT]"></td>
        <td><a href="{% url 'index:forbidden' %}">flag.txt</a></td>
        <td align="right">09-Jan-2019 08:00  </td>
        <td align="right"> 58 </td><td>&nbsp;</td>
    </tr>
    <tr>
        <td valign="top"><img src="" alt="[   ]"></td>
        <td><a href="{% url 'index:forbidden' %}">index.txt</a></td>
        <td align="right">09-Jan-2019 08:00  </td><td align="right">1.0K</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <th colspan="5"><hr></th>
    </tr>
</table>
<address>Apache/2.2.15 Server at Raspberry Pi Port 10080</address>
</body></html>